"""not require data in lanes

Revision ID: 2c21bc2c16d6
Revises: be6f1cfeebc3
Create Date: 2025-04-15 08:49:34.946997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c21bc2c16d6'
down_revision = 'be6f1cfeebc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lanes', schema=None) as batch_op:
        batch_op.alter_column('pickup_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('delivery_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lanes', schema=None) as batch_op:
        batch_op.alter_column('delivery_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('pickup_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###
