"""initial migration

Revision ID: 49597d534e56
Revises: 
Create Date: 2025-04-25 11:37:42.380579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49597d534e56'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carrier_shipper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carrier_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['carrier_user_id'], ['id'])

    with op.batch_alter_table('carriers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))
        
        # FIRST add the new column as nullable
        batch_op.add_column(sa.Column('primary_user_id', sa.Integer(), nullable=True))
        
        # THEN copy values from the old user_id column
        batch_op.execute("UPDATE carriers SET primary_user_id = user_id")
        
        # THEN drop the old foreign key
        batch_op.drop_constraint('carriers_user_id_fkey', type_='foreignkey')
        
        # THEN make the new column NOT NULL
        batch_op.alter_column('primary_user_id', nullable=False)
        
        # Create new foreign key
        batch_op.create_foreign_key(None, 'users', ['primary_user_id'], ['id'])
        
        # Finally drop the old column
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carrier_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'carriers', ['carrier_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('carrier_id')

    with op.batch_alter_table('carriers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('carriers_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('primary_user_id')
        batch_op.drop_column('deleted')

    with op.batch_alter_table('carrier_shipper', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('carrier_user_id')

    # ### end Alembic commands ###
