"""Reset: add active field

Revision ID: 749411a6be55
Revises: 
Create Date: 2025-03-25 10:45:51.973578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749411a6be55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
