"""remove dnus field

Revision ID: 7b0c9a958823
Revises: 0e2693a1628f
Create Date: 2025-03-27 10:02:04.230975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b0c9a958823'
down_revision = '0e2693a1628f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carriers', schema=None) as batch_op:
        batch_op.drop_constraint('carriers_duns_key', type_='unique')
        batch_op.drop_column('duns')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carriers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duns', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('carriers_duns_key', ['duns'])

    # ### end Alembic commands ###
