"""id shipper

Revision ID: a225c85595e1
Revises: 6c80c8109685
Create Date: 2025-04-28 16:05:03.283306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a225c85595e1'
down_revision = '6c80c8109685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipper_id', sa.Integer(), nullable=True))
        batch_op.drop_index('idx_users_email')
        batch_op.drop_index('ix_users_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_email', ['email'], unique=True)
        batch_op.create_index('idx_users_email', ['email'], unique=False)
        batch_op.drop_column('shipper_id')

    # ### end Alembic commands ###
