"""recreating missing migration

Revision ID: be6f1cfeebc3
Revises: 535311fd2577
Create Date: 2025-04-10 16:10:55.760830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6f1cfeebc3'
down_revision = '535311fd2577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shippers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('shippers', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
