"""add leave_open_for columns to lanes

Revision ID: c9041f35e721
Revises: a3ddae4afb86
Create Date: 2025-04-24 09:12:31.492589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9041f35e721'
down_revision = 'a3ddae4afb86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carriers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True, server_default='false'))

    with op.batch_alter_table('lanes', schema=None) as batch_op:
        # Convert JSONB to Integer with proper handling
        batch_op.alter_column('additional_stops',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using="""
                   CASE 
                       WHEN additional_stops::text ~ '^[0-9]+$' THEN (additional_stops::text)::integer
                       ELSE NULL
                   END
               """)
        
        batch_op.alter_column('leave_open_for_option',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('leave_open_for_number',
               existing_type=sa.NUMERIC(precision=100, scale=0),
               nullable=True)
        batch_op.drop_column('open_value')
        batch_op.drop_column('open_unit')

    # Set default value for existing records
    op.execute("UPDATE carriers SET deleted = false WHERE deleted IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lanes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('open_unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('open_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.alter_column('leave_open_for_number',
               existing_type=sa.NUMERIC(precision=100, scale=0),
               nullable=False)
        batch_op.alter_column('leave_open_for_option',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('additional_stops',
               existing_type=sa.Integer(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using="to_jsonb(additional_stops::text)")

    with op.batch_alter_table('carriers', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###