"""many to many relationship quote-carrier

Revision ID: de75ee732df1
Revises: eddd4bfdad1e
Create Date: 2025-03-31 15:26:19.849880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de75ee732df1'
down_revision = 'eddd4bfdad1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('equipment_type', sa.String(length=50), nullable=False),
    sa.Column('temp_controlled', sa.Boolean(), nullable=True),
    sa.Column('rate_type', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('pickup_date', sa.DateTime(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=False),
    sa.Column('commodity', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('declared_value', sa.Float(), nullable=True),
    sa.Column('additional_stops', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('accessorials', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_carrier',
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('quote_id', 'carrier_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote_carrier')
    op.drop_table('quotes')
    # ### end Alembic commands ###
