"""create city table

Revision ID: eddd4bfdad1e
Revises: db96ce9eccf4
Create Date: 2025-03-31 14:28:54.535879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eddd4bfdad1e'
down_revision = 'db96ce9eccf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('postal_type', sa.String(length=10), nullable=True),
    sa.Column('city_name', sa.String(length=100), nullable=False),
    sa.Column('city_type', sa.String(length=10), nullable=True),
    sa.Column('county_name', sa.String(length=100), nullable=True),
    sa.Column('county_fips', sa.String(length=10), nullable=True),
    sa.Column('province_name', sa.String(length=100), nullable=True),
    sa.Column('province_abbr', sa.String(length=10), nullable=True),
    sa.Column('state_fips', sa.String(length=10), nullable=True),
    sa.Column('msa_code', sa.String(length=10), nullable=True),
    sa.Column('area_code', sa.String(length=20), nullable=True),
    sa.Column('time_zone', sa.String(length=50), nullable=True),
    sa.Column('utc', sa.String(length=10), nullable=True),
    sa.Column('dst', sa.String(length=5), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lanes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipper_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('equipment_type', sa.String(length=50), nullable=False),
    sa.Column('temp_controlled', sa.Boolean(), nullable=True),
    sa.Column('rate_type', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('pickup_date', sa.DateTime(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=False),
    sa.Column('commodity', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('declared_value', sa.Float(), nullable=True),
    sa.Column('additional_stops', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('leave_open_for_option', sa.String(length=100), nullable=False),
    sa.Column('leave_open_for_number', sa.Numeric(precision=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shipper_id'], ['shippers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lane_accessorials',
    sa.Column('lane_id', sa.Integer(), nullable=False),
    sa.Column('accessorial_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accessorial_id'], ['accessorials.id'], ),
    sa.ForeignKeyConstraint(['lane_id'], ['lanes.id'], ),
    sa.PrimaryKeyConstraint('lane_id', 'accessorial_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lane_accessorials')
    op.drop_table('lanes')
    op.drop_table('cities')
    # ### end Alembic commands ###
