"""add open_unit and open_value to quote 

Revision ID: f676dadd8dc0
Revises: de75ee732df1
Create Date: 2025-04-01 10:29:24.498009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f676dadd8dc0'
down_revision = 'de75ee732df1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('open_unit', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('open_value', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_column('open_value')
        batch_op.drop_column('open_unit')

    # ### end Alembic commands ###
